# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only

---
# tasks file for roles/vcd_gateway_services

- name: create gateway services
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: firewall
     service_params:
        - name: test_firewall
          action: accept
          type: User
          enabled: True
          logging_enabled: False
          source_values:
            - ip:
                - "192.168.110.102-192.168.110.115"
          destination_values:
            - gatewayinterface:
                - "external-network-3"
          services:
            - tcp:
                source_port: any
                destination_port: any
        - name: test_firewall_2
          action: accept
          type: User
          enabled: True
          logging_enabled: False
          source_values:
            - ip:
                - "192.168.110.102-192.168.110.115"
          destination_values:
            - gatewayinterface:
                - "external-network-3"
          services:
            - tcp:
                source_port: any
                destination_port: any
     state: present
  register: output

- name: create gateway services output
  debug:
    msg: '{{ output }}'

- name: update gateway services
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: firewall
     service_params:
        - name: test_firewall
          source_values:
            - gatewayinterface:
                - "external-network-3"
          destination_values:
            - ip:
                - "192.168.110.102-192.168.110.115"
          services:
            - tcp:
                source_port: any
                destination_port: any
        - name: test_firewall_2
          source_values:
            - gatewayinterface:
                - "external-network-3"
          destination_values:
            - ip:
                - "192.168.110.102-192.168.110.115"
          services:
            - tcp:
                source_port: any
                destination_port: any
     state: update
  register: output

- name: update gateway services output
  debug:
    msg: '{{ output }}'

- name: list gateway firewalls
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: firewall
     operation: list
  register: output

- name: list gateway services output
  debug:
    msg: '{{ output }}'

- name: delete gateway services
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: firewall
     service_params:
        - name: test_firewall
        - name: test_firewall_2
     state: absent
  register: output

- name: delete gateway services output
  debug:
    msg: '{{ output }}'

- name: list gateway services
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: firewall
     operation: list
  register: output

- name: list gateway services output
  debug:
    msg: '{{ output }}'

- name: create nat rule
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     service_params:
        - action: snat
          original_address: 10.172.17.11
          translated_address: 192.168.11.1
     state: present
  register: output

- name: create gateway services output
  debug:
    msg: '{{ output }}'

- name: list nat rules
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     operation: list
  register: output

- name: list nat rules output
  debug:
    msg: '{{ output }}'

- name: update nat rule
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     service_params:
        - nat_rule_id: "{{ output.get('msg')[0]['ID'] }}"
          original_address: 10.172.17.20
          translated_address: 192.168.11.50
     state: update
  register: output

- name: update nat rule output
  debug:
    msg: '{{ output }}'

- name: list nat rules
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     operation: list
  register: output

- name: list nat rules output
  debug:
    msg: '{{ output }}'

- name: delete nat rule
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     service_params:
        - nat_rule_id: "{{ output.get('msg')[0]['ID'] }}"
     state: absent
  register: output

- name: delete nat rule output
  debug:
    msg: '{{ output }}'

- name: list nat rules
  vcd_gateway_services:
     user: acmeadmin
     password: XXXXXXXXXXXX
     org: Acme
     vdc: ACME_PAYG
     gateway: edge-gateway
     service: nat_rule
     operation: list
  register: output

- name: list nat rules output
  debug:
    msg: '{{ output }}'